import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#d9d9d9",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  title: {
    marginTop: 10,
    fontSize: 22,
    fontWeight: "bold",
    color: "#000",
    marginVertical: 10,
    textAlign: "center",
  },
  filtersContainer: {
    flexDirection: "row",
    justifyContent: "flex-start",
    width: "90%",
    marginBottom: 10,
    gap: 10,
  },
  input: {
    backgroundColor: "#fff",
    padding: 10,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#ccc",
    width: "30%",
    textAlign: "center",
  },
  pickerContainer: {
    backgroundColor: "#fff",
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#ccc",
    width: "30%",
    padding: 5,
  },
  table: {
    backgroundColor: "white",
    borderRadius: 10,
    padding: 10,
    marginBottom: 20,
    width: 2000,
    borderWidth: 2,
    borderColor: "#019edf",
  },
  headerRow: {
    flexDirection: "row",
    backgroundColor: "#019edf",
    paddingVertical: 10,
    borderBottomWidth: 2,
    borderBottomColor: "#fff",
  },
  headerCell: {
    flex: 1,
    fontWeight: "bold",
    color: "white",
    textAlign: "center",
    padding: 5,
    borderRightWidth: 1,
    borderRightColor: "#fff",
  },
  headerGroup: {
    flex: 2,
    justifyContent: "center",
    alignItems: "center",
    borderRightWidth: 1,
    borderRightColor: "#fff",
  },
  headerCellBig: {
    fontWeight: "bold",
    color: "white",
    textAlign: "center",
    padding: 5,
    backgroundColor: "#019edf",
    width: "100%",
  },
  subHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: "#017bb5",
    width: "100%",
    paddingVertical: 5,
    borderBottomWidth: 1,
    borderBottomColor: "#fff",
  },
  subHeaderCell: {
    flex: 1,
    fontWeight: "bold",
    color: "white",
    textAlign: "center",
    padding: 5,
    borderRightWidth: 1,
    borderRightColor: "#fff",
  },
  buttonsContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    marginTop: 10,
    marginBottom: 20,
    gap: 20,
  },
  button: {
    backgroundColor: "#019edf",
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderRadius: 25,
    width: "40%",
    alignItems: "center",
  },
});
